version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:80"
    depends_on:
        - polls_app
        - api_app

  # Image for polls
  polls_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=<your_password>
      - POSTGRES_USER=<your_user>
      - POSTGRES_DB=<your_db>
  polls_app:
    image: ryanfeb/isolated-app
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    depends_on:
      - polls_db
    environment:
      - DATABASE_URL=postgres://user:user@polls_db/user

  polls_migration:
    image: ryanfeb/isolated-app
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - polls_db
    environment:
      - DATABASE_URL=postgres://user:user@polls_db/user

  # Image for API
  api_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=<your_password>
      - POSTGRES_USER=<your_user>
      - POSTGRES_DB=<your_db>
  api_app:
    image: ryanfeb/isolated-app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - api_db
    environment:
      - DATABASE_URL=postgres://user:user@api_db/user

  api_migration:
    image: ryanfeb/isolated-app
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - api_db
    environment:
      - DATABASE_URL=postgres://user:user@api_db/user
